config/routes.rb
RedditClone::Application.routes.draw do
  
  resources :users, only: [:new, :index, :create, :destroy]
  
  resource :session, only: [:create, :destroy, :new]
  
  shallow do 
    resources :subs do 
      resources :posts do
        resources :comments, only: [:new, :create, :edit, :update, :destroy] do
          resources :comments, only: :new
        end
      end
    end
  end
  

  
  
  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :content, :submitter, :post_id, presence: true
  
  belongs_to :post
  belongs_to :submitter, class_name: "User", foreign_key: :submitter_id
  
  has_many :child_comments, class_name: "Comment", foreign_key: :parent_comment_id
  
  belongs_to :parent_comment, class_name: "Comment", foreign_key: :parent_comment_id
  
  
  
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :sub, class_name: "Sub", foreign_key: :sub_id
  belongs_to :submitter, class_name: "User", foreign_key: :submitter_id
  
  validates :title, :sub_id, :submitter_id, presence: true
  validates :title, uniqueness: { scope: :sub_id }
  
  has_many :comments
  
  
  has_many( :top_level_comments,
            -> { where parent_comment_id: nil},
            class_name: "Comment",
            foreign_key: :post_id
          )
end

app/models/sub.rb
class Sub < ActiveRecord::Base
  belongs_to :moderator, class_name: "User", foreign_key: :moderator_id
  
  validates :title, :description, :moderator_id, presence: true
  validates :title, uniqueness: true
  
  has_many :posts
end

app/models/user.rb
class User < ActiveRecord::Base
  before_validation :ensure_session_token
  validates :username, :password_digest, presence: true 
  validates :password, length: { minimum: 6, allow_nil: true }
  
  has_many :subs, class_name: "Sub", foreign_key: :moderator_id
  
  has_many :posts, class_name: "Post", foreign_key: :submitter_id
  
  has_many :comments, class_name: "Comment", foreign_key: :submitter_id
  
  
  attr_reader :password
  
  
  def self.generate_session_token
    SecureRandom.urlsafe_base64(16)
  end
  
  
  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end
  
  def password=(unencrypted_password)
    @password = unencrypted_password
    self.password_digest = BCrypt::Password.create(unencrypted_password)
    
  end
  
  
  def is_password?(unencrypted_password)
    BCrypt::Password.new(self.password_digest)
                    .is_password?(unencrypted_password)
    
  end
  
  
  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  
  
end

app/models/vote.rb
class Vote < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :signed_in?, :current_user, :moderator?, :editor?
  
  def current_user
    return nil unless session[:token]
    @current_user ||= User.find_by(session_token: session[:token])
  end
  
  def sign_in(user)
    @current_user = user
    session[:token] = user.reset_session_token!
  end
  
  def sign_out
    @current_user = nil
    current_user.reset_session_token!
    session[:token] = nil 
  end
  
  def signed_in?
    !!current_user
  end
  
  def moderator?
    @sub = Sub.find(params[:id])
    current_user == @sub.moderator
  end
  
  def ensure_editor
    @post = Post.find(params[:id])
    redirect_to post_url(@post) unless editor?
  end
  
  def editor?
    @post = Post.find(params[:id])
    current_user == @post.submitter || moderator?
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
   
  before_action :ensure_editor, only: [:edit, :update, :destroy]
 
  def new
    
    if params.keys.include? "comment_id"
      @comment = Comment.find(params[:comment_id]).child_comments.new
      @post = @comment.parent_comment.post
      
      
    else
      @post = Post.find(params[:post_id])
      @comment = Comment.new
    end
      
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.submitter = current_user
    
    if @comment.save
      redirect_to post_url(@comment.post)
    else
      flash.now[:errors] = @comment.errors.full_messages
      render :new
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @post = @comment.post
    @comment.destroy
    
    redirect_to post_url(@post)
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update_attributes(comment_params)
      redirect_to post_url(@comment.post)
    else
      flash.now[:errors] = @comment.errors.full_messages
      render :edit
    end
  end
  
  
  private
  
  def comment_params
    params.require(:comment).permit(:content, :post_id, :parent_comment_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :ensure_editor, only: [:edit, :update, :destroy]
  
  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    @post.sub_id = params[:sub_id]
    
    if @post.save
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
    
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      redirect_to post_url(@post)
    else
      flash[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @sub = @post.sub
    @post.destroy
    
    redirect_to sub_url(@sub)
  end

  def show
    @post = Post.find(params[:id])
    @all_comments = hashify_comments(@post.comments)
  end
  
  
  private
  
  def post_params
    params.require(:post).permit(:title, :url, :content)
  end
  
  
  def hashify_comments(comments)
    h = {}
    
    comments.each do |comment|
      h[comment.parent_comment_id] ||= []
      h[comment.parent_comment_id] << comment
    end
    
    h
    
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_by(username: params[:user][:username] )
    if @user && @user.is_password?(params[:user][:password])
      sign_in(@user)
      redirect_to users_url
    else
      flash.now[:errors] = ["Invalid credentials"]
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to new_session_url
  end
  
  def new
    @user = User.new
  end
  
  
  
  
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :ensure_moderator, only: [:edit, :update, :destroy]
  
  
  def edit
    @sub = Sub.find(params[:id])
  end

  def create
    @sub = current_user.subs.new(sub_params)
    
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def new
    @sub = Sub.new
  end

  def destroy
    Sub.find(params[:id]).destroy
    
    redirect_to subs_url
  end

  def update
    @sub = Sub.find(params[:id])
    
    if @sub.update_attributes(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
    
  end

  def index
    @subs = Sub.all
  end
  
  def show
    @sub = Sub.find(params[:id])
    @post = Post.new
  end
  
  
  
  private
  
  def sub_params
    params.require(:sub).permit(:title, :description)
  end
  
  
  def ensure_moderator
    @sub = Sub.find(params[:id])
    redirect_to sub_url(@sub) unless moderator?
  end
  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def index
    @users = User.all
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in(@user)
      redirect_to users_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def destroy
  end
  
  
  private
  
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<p><b><%= comment.submitter.username %></b> => <%= comment.content %></p>
<p><%= comment.updated_at || comment.created_at %></p>
<% if editor?  %>
  <p><%= link_to "Edit Comment", edit_comment_url(comment) %></p> 
<% end %>  

<p><%= link_to "Add Comment", new_comment_comment_url(comment) %></p>

<ul> 
  <% if @all_comments[comment.id] %>
    <% @all_comments[comment.id].each do |child|  %>
  
      <li><%= render "comments/comment", comment: child %></li>
  
    <% end %>
  <% end %>
</ul>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>

  <form action="<%= comment_url(@comment) %>" method="POST">
    
    <input type="hidden" name="_method" value="PATCH">
    
    <input 
      type="hidden"
      name="authenticity_token"
      value="<%= form_authenticity_token %>">
  
    <br>
  
    <textarea 
      rows="10" cols="100" 
      name="comment[content]">
      <%= @comment.content %>
    </textarea>

    <br><br> 
    
    <button>Edit Comment!</button>

</form>
  
<%= button_to "Delete Comment", comment_url(@comment), method: "delete" %>

app/views/comments/new.html.erb
<% if signed_in? %>
  <h3>New Comment</h3>

  <form action="<%= post_comments_url(@post) %>" method="POST">

    <input 
      type="hidden"
      name="authenticity_token"
      value="<%= form_authenticity_token %>">
  
    <input type="hidden" 
      name="comment[post_id]" 
      value="<%= @post.id  %>">

      <br>
      
    <input type="hidden" 
      name="comment[parent_comment_id]" 
      value="<%= @comment.parent_comment_id %>">

      
      <br>
  
    <textarea rows="10" cols="100" name="comment[content]"><%= @comment.content %> </textarea>

    <br><br> 
    
    <button>Comment!</button>

  </form>
  
<% end %>

app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <% unless flash[:errors].nil? %>
     
      <% flash[:errors].each do |msg| %>
        <p><%= msg %></p>
      <% end %>
      
    <% end %>
    
    <% if signed_in? %>

      <%= current_user.username %>
      <%= button_to "Sign Out", session_url, method: "delete" %>
      
      <%= link_to "Create Sub", new_sub_url %>
      <%= link_to "Subs Index", subs_url %>
      
      
    <% else %>
      <%= link_to "Sign Up", new_user_url %>
      <%= link_to "Sign In", new_session_url %>
    
    <% end %>

    <%= yield %>

  </body>
</html>

app/views/posts/_editor.html.erb
<% if editor? %>

  <%= "Hi #{current_user.username}! You are authorized to edit this post" %>

  <h3>Edit Post</h3>

  <form action="<%= post_url(@post) %>" method="POST">
   
    <input type="hidden" name="_method" value="PATCH">
    
    <input 
      type="hidden"
      name="authenticity_token"
      value="<%= form_authenticity_token %>">
  
    <label>Title
      <br>
      
      <input type="text" name="post[title]" value="<%= @post.title %>">
    </label>
    
    <br><br>
    
    <label>Url
      <br>
      
      <input type="text" name="post[url]" value="<%= @post.url %>"
    </label>
   
    <br><br>
    
    <label>Content
      <br>
      
        <textarea name="post[content]"><%= @post.content %> </textarea>
    </label>
  
    <br><br>
    
    <button>Edit Post!</button>
  
  </form>
  
  <br><br>
  
  <%= button_to "Delete Post", post_url(@post), method: "delete" %>

  
<% end %>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

app/views/posts/new.html.erb
<h1>Posts#new</h1>
<p>Find me in app/views/posts/new.html.erb</p>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><a href="http://<%= @post.url %>"><%= @post.url %></a></p>
<p><%= @post.content %></p>

<%= render "editor" %>

<br><br>
<%= link_to "Post Comment", new_post_comment_url(@post)  %>

<ul>
  <% @all_comments[nil].each do |comment| %>
    <li>
      <%= render comment %>
    </li>
    
  <% end %>
</ul>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>

app/views/subs/_moderator_label.html.erb
<% if moderator? %>

  <%= "Hi #{current_user.username}! You are the moderator for this Sub" %>
  <%= link_to "Edit Sub", edit_sub_url(@sub)%>
  
<% end %>

app/views/subs/_post_form.html.erb
<h3>Create Post</h3>

<form action="<%= sub_posts_url(@sub) %>" method="POST">
  <input 
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">
  
  <label>Title
    <input type="text" name="post[title]" value="<%= @post.title %>">
  
  </label>
  <label>Url
    
    <input type="text" name="post[url]" value="<%= @post.url %>"
  
  </label>
  <label>Content
    
      <textarea name="post[content]"><%= @post.content %> </textarea>
  
  </label>
  
  <button>Post!</button>
  
</form>

app/views/subs/_posts_index.html.erb
<h3>Posts</h3>

<ul>
<% @sub.posts.each do |post| %>
  <li><%= link_to post.title, post_url(post) %> </li>
<% end %>
</ul>

app/views/subs/create.html.erb
<h1>Subs#create</h1>
<p>Find me in app/views/subs/create.html.erb</p>

app/views/subs/destroy.html.erb
<h1>Subs#destroy</h1>
<p>Find me in app/views/subs/destroy.html.erb</p>

app/views/subs/edit.html.erb
<h1>Edit Sub</h1>

<form action="<%= sub_url(@sub) %>" method="POST">
  <input type="hidden" name="_method" value="PATCH">
  
  <input 
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">
  
  <label>Title
    <input type="text" name="sub[title]" value="<%= @sub.title %>">
  </label>
  
  <label>Description
    <textarea name="sub[description]">
      <%= @sub.description %>
    </textarea>
  </label>
  
  <button>Edit Sub</button>
  
</form>

<br><br>

<%= button_to "Delete Sub", sub_url(@sub), method: "delete" %>

app/views/subs/index.html.erb
<h1>All Subs</h1>
<ul>
  <% @subs.each do |sub| %>
    <marquee><li><%= link_to "#{sub.title}", sub_url(sub) %></li></marquee>
  <% end %>
</ul>

app/views/subs/new.html.erb
<h1>Create Sub</h1>

<form action="<%= subs_url %>" method="POST">
  
  <input 
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">
  
  <label>Title
    <input type="text" name="sub[title]" value="<%= @sub.title %>">
  </label>
  
  <label>Description
    <textarea name="sub[description]">
      <%= @sub.description %>
    </textarea>
  </label>
  
  <button>Create Sub</button>
  
</form>

app/views/subs/show.html.erb
<h1><marquee><%= @sub.title %></marquee></h1>
<%= render "moderator_label" %>

<p>Description:</p>
<p><%= @sub.description %></p>

<%= render partial: "post_form" %>
<%= render partial: "posts_index" %>

app/views/subs/update.html.erb
<h1>Subs#update</h1>
<p>Find me in app/views/subs/update.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/index.html.erb
<h1>Users</h1>
<% @users.each do |user| %>
  <p><%= user.username %></p>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="<%= users_url %>" method="POST">
  
  <input 
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">
  
  <label>Username
    <input type="text" name="user[username]" value="<%= @user.username %>">
  </label>
  
  <label>Password
    <input type="password" name="user[password]" value="<%= @user.password %>">
  </label>
  
  <button>Sign Up</button>
  
</form>